import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-semiconductor-mask-nre-charge-audit",
  "engine": "recovery",
  "title": "Semiconductor Mask & NRE Charge Audit",
  "shortTitle": "Semiconductor Mask and NRE Charge Audit",
  "tagline": "Validate mask, tape-out, engineering, and nonrecurring charges against milestones, ownership, respin responsibility, and waivers.",
  "industry": "Semiconductor Procurement Recovery",
  "buyer": "Fabless semiconductor companies and OEMs",
  "uiPort": 4705,
  "apiPort": 5705,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Semiconductor Mask & NRE Charge Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits in one accountable workflow. Validate mask, tape-out, engineering, and nonrecurring charges against milestones, ownership, respin responsibility, and waivers.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Semiconductor Mask & NRE Charge Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("foundry-agreement-library","SMN01","Foundry agreement library","Execute foundry agreement library using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed foundry agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Foundry agreement library Reference","text","SMN01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("tape-out-program-registry","SMN02","Tape-out program registry","Execute tape-out program registry using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed tape-out program registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Tape-out program registry Reference","text","SMN02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("mask-set-inventory","SMN03","Mask set inventory","Execute mask set inventory using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed mask set inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Mask set inventory Reference","text","SMN03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("layer-count-validation","SMN04","Layer count validation","Execute layer count validation using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed layer count validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Layer count validation Reference","text","SMN04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("nre-milestone-tracking","SMN05","NRE milestone tracking","Execute nre milestone tracking using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed nre milestone tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","NRE milestone tracking Reference","text","SMN05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("engineering-lot-calculation","SMN06","Engineering lot calculation","Execute engineering lot calculation using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed engineering lot calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Engineering lot calculation Reference","text","SMN06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("respins-responsibility","SMN07","Respins responsibility","Execute respins responsibility using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed respins responsibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Respins responsibility Reference","text","SMN07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("design-change-attribution","SMN08","Design change attribution","Execute design change attribution using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed design change attribution decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Design change attribution Reference","text","SMN08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("waiver-credit-control","SMN09","Waiver credit control","Execute waiver credit control using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed waiver credit control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Waiver credit control Reference","text","SMN09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("tooling-ownership-evidence","SMN10","Tooling ownership evidence","Execute tooling ownership evidence using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed tooling ownership evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Tooling ownership evidence Reference","text","SMN10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("invoice-matching","SMN11","Invoice matching","Execute invoice matching using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Invoice matching Reference","text","SMN11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("duplicate-nre-detection","SMN12","Duplicate NRE detection","Execute duplicate nre detection using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed duplicate nre detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Duplicate NRE detection Reference","text","SMN12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("foundry-dispute-workflow","SMN13","Foundry dispute workflow","Execute foundry dispute workflow using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed foundry dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Foundry dispute workflow Reference","text","SMN13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("credit-reconciliation","SMN14","Credit reconciliation","Execute credit reconciliation using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Credit reconciliation Reference","text","SMN14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]}),
feature("program-node-analytics","SMN15","Program node analytics","Execute program node analytics using foundry agreements, tape-outs, mask sets, engineering lots, NRE milestones, respins, ownership, waivers, invoices, and credits.","Produce a governed program node analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Foundry / Tape-Out Program","text","Foundry / Tape-Out Program · Standard Case"],["caseReference","Program node analytics Reference","text","SMN15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1360000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1645600],["domainDriver","NRE Event","select","Initial mask set",["Initial mask set","Respins","Engineering lot"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Foundry agreement library case","Tape-out program registry case","Mask set inventory case","Layer count validation case","NRE milestone tracking case"]})
]);
